/**
 * The verification suite. Real Chromium, real Worker, real Pyodide, the real
 * pinned wheel — no mocked Python anywhere.
 *
 * It answers three separate questions, and they are not interchangeable:
 *
 * 1. **Is it the right answer?** Values a person read off the filings, repeated
 *    from `tests/test_golden.py`.
 * 2. **Is it the same answer as CPython?** Whole-output parity against
 *    `test/expected/cases.json`, generated by running the same bridge module on
 *    the host. This is what would catch wasm-lxml parsing a filing differently.
 * 3. **Does the boundary behave?** One runtime, warm reuse, transferred bytes,
 *    error conversion, cancellation, no leaks, a clean console.
 */
import {
  test,
  expect,
  expectedCases,
  pick,
  contains,
  DAL_1997_ROLES,
  DAL_1997_EXPECTED,
  DAL_1994_EXPECTED,
  CMP_2024_ROLES,
  CMP_2024_EXPECTED,
  AZZ_2019_ROLES,
  AZZ_2019_EXPECTED,
  CVS_1996_ROLES,
  CVS_1996_EXPECTED,
  AAPL_2003_ROLES,
  AAPL_2003_EXPECTED,
  type CaseId,
  type ExtractionResult,
} from "./fixtures.js";
import {
  LXML_VERSION,
  PROTOCOL_VERSION,
  PYODIDE_VERSION,
  PYTHON_VERSION,
  SEC_TABLES_VERSION,
  WHEEL_SHA256,
} from "../../src/pin.js";

const CASES = expectedCases as Record<
  string,
  { url: string; filingDate: string; profile: string; documentBytes: number; expected: any }
>;

async function extractCase(page: any, id: CaseId): Promise<ExtractionResult> {
  const c = CASES[id];
  return page.evaluate(
    (call: any) => window.secBridge.extract(call),
    { url: c.url, filingDate: c.filingDate, profile: c.profile },
  );
}

/** The result minus the two timing fields, which are measurements not results. */
function withoutTiming(result: ExtractionResult) {
  const { preparationMs, executionMs, ...rest } = result;
  return rest;
}

test.afterEach(async ({ harness, browserErrors }) => {
  const inPage = await harness.evaluate(() => window.secBridge.consoleErrors());
  expect([...browserErrors, ...inPage], "browser console must stay clean").toEqual([]);
});

// ---------------------------------------------------------------------------
// Preparation
// ---------------------------------------------------------------------------

test("cold preparation loads the pinned runtime and reports what it loaded", async ({
  harness,
}) => {
  const info = await harness.evaluate(() => window.secBridge.prepare());

  // Asserted against the pins rather than against literals repeated here: the
  // question is whether the runtime is the one that was pinned, and a second
  // copy of the numbers could only ever drift away from the first.
  expect(info.initializedRuntime).toBe(true);
  expect(info.protocolVersion).toBe(PROTOCOL_VERSION);
  expect(info.pyodideVersion).toBe(PYODIDE_VERSION);
  expect(info.pythonVersion).toBe(PYTHON_VERSION);
  expect(info.lxmlVersion).toBe(LXML_VERSION);
  expect(info.secTablesVersion).toBe(SEC_TABLES_VERSION);
  expect(info.wheelSha256).toBe(WHEEL_SHA256);
  // The three profiles the library registers, straight from `available_tables()`.
  expect(info.availableProfiles).toEqual([
    "beneficial_ownership",
    "director_compensation",
    "summary_compensation",
  ]);
});

test("two simultaneous preparations initialize exactly one runtime", async ({ harness }) => {
  const [first, second] = await harness.evaluate(() => window.secBridge.prepareTwice());

  // Both callers get a usable runtime...
  expect(first.secTablesVersion).toBe("0.3.0");
  expect(second.secTablesVersion).toBe("0.3.0");
  // ...but only one of them built it. The other joined the same initialisation
  // rather than starting a second interpreter beside it.
  expect([first.initializedRuntime, second.initializedRuntime]).toEqual([true, false]);

  const diagnostics = await harness.evaluate(() => window.secBridge.diagnostics());
  expect(diagnostics.runtimeInitCount).toBe(1);
});

test("a wheel that fails its checksum is refused", async ({ harness }) => {
  // Same wheel, one byte flipped in transit. Nothing may reach the interpreter.
  const outcome = await harness.evaluate(() =>
    window.secBridge.prepareFrom("/py-tampered/"),
  );

  expect(outcome.kind).not.toBe("prepared");
  expect(outcome.message).toContain("checksum mismatch");
  expect(outcome.message).toContain("Refusing to install");
});

// ---------------------------------------------------------------------------
// Extraction — the answers themselves
// ---------------------------------------------------------------------------

test("ASCII: Delta 1997, values as read off the filing", async ({ harness }) => {
  const result = await extractCase(harness, "dal_1997_sct");

  expect(result.ok).toBe(true);
  expect(result.backend).toBe("ascii");
  expect(result.era).toBe("pre2006");
  expect(result.rows).toHaveLength(15);
  expect(new Set(result.rows.map((r) => r[0])).size).toBe(5);

  const got = pick(result, DAL_1997_ROLES);
  for (const row of DAL_1997_EXPECTED) expect(contains(got, row)).toBe(true);

  // LTIP is a real zero here; missing would be "". The distinction is load-bearing.
  const ltip = pick(result, ["ltip_payouts"]).map((r) => r[0]);
  expect(new Set(ltip)).toEqual(new Set(["0"]));
});

test("ASCII: Delta 1994, the indented-ruler regression", async ({ harness }) => {
  const result = await extractCase(harness, "dal_1994_sct");

  expect(result.ok).toBe(true);
  expect(result.era).toBe("pre2006");
  const got = pick(result, DAL_1997_ROLES);
  for (const row of DAL_1994_EXPECTED) expect(contains(got, row)).toBe(true);

  // Names must not be truncated by reading the ruler at face value.
  const names = result.rows.map((r) => r[0]);
  expect(names.some((n) => n.startsWith("ald ") || n.startsWith("arold"))).toBe(false);
  // Years must not be split into "19"/"94" by over-correcting for it.
  const years = new Set(pick(result, ["year"]).map((r) => r[0]));
  for (const y of years) expect(["1994", "1993", "1992"]).toContain(y);
});

test("SGML: Alaska Air 1994 selects the SGML backend", async ({ harness }) => {
  const result = await extractCase(harness, "alk_1994_sgml_sct");

  // The backend that exists because old EDGAR <TABLE> blocks close no rows or
  // cells, so lxml cannot see the table at all.
  expect(result.backend).toBe("sgml");
  expect(result.ok).toBe(true);
  expect(result.era).toBe("pre2006");
  expect(result.rows.length).toBe(17);
  expect(result.provenance).toContain("sgml_source");
  expect(result.reviewRequired).toBe(false);
});

test("DOM: Compass Minerals 2024 director compensation, all ten directors", async ({
  harness,
}) => {
  const result = await extractCase(harness, "cmp_2024_director_comp");

  expect(result.ok).toBe(true);
  expect(result.backend).toBe("dom"); // lxml, compiled to wasm, doing real work
  expect(result.profile).toBe("director_compensation");
  expect(result.reviewRequired).toBe(false);
  expect(result.rows).toHaveLength(10);

  const got = pick(result, CMP_2024_ROLES);
  for (const row of CMP_2024_EXPECTED) expect(contains(got, row)).toBe(true);

  // Independent arithmetic: every row's components sum to its stated total.
  for (const [, fees, stock, total] of got) {
    const parts = Number(fees || 0) + Number(stock || 0);
    expect(Math.abs(parts - Number(total))).toBeLessThan(1);
  }
  // The director schema, not the SCT that outscores it on trailing columns.
  expect(result.columns).toContain("fees_earned");
  expect(result.columns).not.toContain("salary");
});

test("DOM: AZZ 2019 beneficial ownership keeps the address out of the name", async ({
  harness,
}) => {
  const result = await extractCase(harness, "azz_2019_ownership");

  expect(result.ok).toBe(true);
  expect(result.profile).toBe("beneficial_ownership");
  expect(result.reviewRequired).toBe(false);
  expect(result.columns).toEqual(expect.arrayContaining(["holder_name", "shares", "percent"]));
  expect(result.columns).not.toContain("year"); // ownership has no year dimension

  const got = pick(result, AZZ_2019_ROLES);
  for (const row of AZZ_2019_EXPECTED) expect(contains(got, row)).toBe(true);
  for (const [name] of got) {
    expect(name).not.toContain("Street");
    expect(name).not.toContain(" 52 nd");
  }
});

test("ASCII: CVS 1996 ownership, three holders and no footnote prose", async ({ harness }) => {
  const result = await extractCase(harness, "cvs_1996_ownership");

  expect(result.ok).toBe(true);
  expect(result.backend).toBe("ascii");
  expect(result.rows).toHaveLength(3);
  const got = pick(result, CVS_1996_ROLES);
  for (const row of CVS_1996_EXPECTED) expect(contains(got, row)).toBe(true);

  // Each holder keeps its own address; FMR's must not leak onto Brinson.
  const byName = new Map(
    pick(result, ["holder_name", "holder_address"]).map(([name, address]) => [name, address]),
  );
  expect(byName.get("FMR Corp.(1)")).toContain("82 Devonshire");
  expect(byName.get("Brinson Partners, Inc.(2)")).toContain("LaSalle");
  expect(byName.get("Brinson Partners, Inc.(2)")).not.toContain("Devonshire");
});

test("DOM: Apple 2003 explodes stacked years into person-years", async ({ harness }) => {
  const result = await extractCase(harness, "aapl_2003_sct_stacked");

  expect(result.ok).toBe(true);
  expect(result.rows).toHaveLength(15); // not 5 rows with three years crushed in
  expect(new Set(result.rows.map((r) => r[0])).size).toBe(5);

  const got = pick(result, AAPL_2003_ROLES);
  for (const row of AAPL_2003_EXPECTED) expect(contains(got, row)).toBe(true);

  // A year with no bonus stays empty rather than pulling the next year's value up.
  const jobs = got.filter(([name]) => name === "Steven P. Jobs");
  expect(new Map(jobs.map(([, year, , bonus]) => [year, bonus])).get("2000")).toBe("");
});

test("all three profiles work through one warm runtime", async ({ harness }) => {
  const profiles = await harness.evaluate(async () => {
    const calls = [
      { url: "/fixtures/dal_1997_sct.txt", filingDate: "1997-09-19", profile: "summary_compensation" },
      { url: "/fixtures/cmp_2024_director_comp.html", filingDate: "2024-01-29", profile: "director_compensation" },
      { url: "/fixtures/azz_2019_ownership.html", filingDate: "2019-05-28", profile: "beneficial_ownership" },
    ] as const;
    const out = [];
    for (const call of calls) out.push(await window.secBridge.extract(call as any));
    return out;
  });

  expect(profiles.map((r) => r.profile)).toEqual([
    "summary_compensation",
    "director_compensation",
    "beneficial_ownership",
  ]);
  expect(profiles.every((r) => r.ok)).toBe(true);
  // Only the first request paid for preparation.
  expect(profiles[0].preparationMs).toBeGreaterThan(0);
  expect(profiles[1].preparationMs).toBe(0);
  expect(profiles[2].preparationMs).toBe(0);

  const diagnostics = await harness.evaluate(() => window.secBridge.diagnostics());
  expect(diagnostics.runtimeInitCount).toBe(1);
});

// ---------------------------------------------------------------------------
// Parity with CPython
// ---------------------------------------------------------------------------

for (const id of Object.keys(CASES) as CaseId[]) {
  test(`parity with CPython: ${id}`, async ({ harness }) => {
    const result = await extractCase(harness, id);
    // Byte-for-byte the same result the same bridge module produces on the host.
    expect(withoutTiming(result)).toEqual(CASES[id].expected);
  });
}

// ---------------------------------------------------------------------------
// The boundary
// ---------------------------------------------------------------------------

test("raw bytes are the primary input path and are transferred, not copied", async ({
  harness,
}) => {
  // A tiny SCT built in the page, never touching the network or a string API.
  const bytes = await harness.evaluate(async () => {
    const response = await fetch("/fixtures/dal_1997_sct.txt");
    return [...new Uint8Array(await response.arrayBuffer())];
  });

  const result = await harness.evaluate(
    (values: number[]) =>
      window.secBridge.extractRawBytes(values, "1997-09-19", "summary_compensation"),
    bytes,
  );

  expect(result.ok).toBe(true);
  expect(result.rows).toHaveLength(15);
  // The caller's ArrayBuffer is detached: the filing crossed the thread once.
  expect(result.detached).toBe(true);
});

test("warm repeat extraction reuses the runtime and is faster than the cold one", async ({
  harness,
}) => {
  const [first, second] = await harness.evaluate(() =>
    window.secBridge.extractTwice({
      url: "/fixtures/cmp_2024_director_comp.html",
      filingDate: "2024-01-29",
      profile: "director_compensation",
    }),
  );

  expect(first.rows).toEqual(second.rows);
  expect(first.preparationMs).toBeGreaterThan(0);
  expect(second.preparationMs).toBe(0);
  // Cold start dominates: preparing the interpreter costs far more than parsing
  // a proxy statement, which is the entire argument for keeping it warm.
  expect(second.executionMs).toBeLessThan(first.preparationMs);

  const diagnostics = await harness.evaluate(() => window.secBridge.diagnostics());
  expect(diagnostics.runtimeInitCount).toBe(1);
  expect(diagnostics.extractionsCompleted).toBe(2);
});

test("a document with no table is a result, not an error", async ({ harness }) => {
  const result = await harness.evaluate(() =>
    window.secBridge.extractRawBytes(
      [...new TextEncoder().encode("<html><body><p>No tables here.</p></body></html>")],
      "2020-01-01",
      "summary_compensation" as any,
    ),
  );

  expect(result.ok).toBe(false);
  expect(result.flags).toContain("no_table_found");
  expect(result.error).toBeUndefined(); // nothing failed; there was nothing to find
  expect(result.rows).toEqual([]);
  expect(result.columns).toEqual([]);
  expect(result.backend).toBeNull();
  expect(result.schemaVersion).toBe(1);
});

test("review flags and provenance flags stay separate", async ({ harness }) => {
  const flagged = await extractCase(harness, "abcp_1997_review_flags");

  expect(flagged.ok).toBe(true);
  expect(flagged.reviewRequired).toBe(true);
  expect(flagged.flags).toEqual(
    expect.arrayContaining(["ambiguous_selection", "missing_required_columns"]),
  );
  // `sgml_source` describes how the answer was obtained. It is not a defect and
  // must not be what makes a result look like it needs review.
  expect(flagged.provenance).toEqual(["sgml_source"]);
  expect(flagged.provenance).not.toContain("ambiguous_selection");

  const clean = await extractCase(harness, "dal_1997_sct");
  expect(clean.provenance).toEqual(["ascii_source"]);
  expect(clean.reviewRequired).toBe(false);
});

test("a Python exception becomes a typed error on a well-formed result", async ({
  harness,
}) => {
  const result = await harness.evaluate(() => window.secBridge.selftest("value_error"));

  expect(result.ok).toBe(false);
  // The Python class name, not "PythonError": the caller should see what raised.
  expect(result.error?.kind).toBe("ValueError");
  expect(result.error?.message).toContain("injected failure");
  // Still a complete ExtractionResult, so a caller has one shape to handle.
  expect(result.schemaVersion).toBe(1);
  expect(result.rows).toEqual([]);
  expect(result.executionMs).toBeGreaterThanOrEqual(0);

  const other = await harness.evaluate(() => window.secBridge.selftest("key_error"));
  expect(other.error?.kind).toBe("KeyError");

  // The runtime survives its own exception: it is still the same interpreter.
  const after = await extractCase(harness, "dal_1997_sct");
  expect(after.ok).toBe(true);
  const diagnostics = await harness.evaluate(() => window.secBridge.diagnostics());
  expect(diagnostics.runtimeInitCount).toBe(1);
});

test("a malformed message is rejected without touching the runtime", async ({ harness }) => {
  const error = await harness.evaluate(() =>
    window.secBridge.sendMalformed({ type: "extract", requestId: "x", document: "not a buffer" }),
  );
  expect(error.kind).toBe("ProtocolError");

  const badDate = await harness.evaluate(() =>
    window.secBridge.sendMalformed({
      type: "extract",
      requestId: "x",
      document: new ArrayBuffer(8),
      filingDate: "2019-02-31",
      profile: "summary_compensation",
    }),
  );
  expect(badDate.kind).toBe("ProtocolError");

  const badProfile = await harness.evaluate(() =>
    window.secBridge.sendMalformed({
      type: "extract",
      requestId: "x",
      document: new ArrayBuffer(8),
      filingDate: "2019-05-28",
      profile: "audit_fees",
    }),
  );
  expect(badProfile.kind).toBe("ProtocolError");
});

// ---------------------------------------------------------------------------
// Cancellation and lifecycle
// ---------------------------------------------------------------------------

test("cancelling terminates the worker, and the rebuilt one extracts correctly", async ({
  harness,
}) => {
  const outcome = await harness.evaluate(() =>
    window.secBridge.cancelMidFlightThenExtract({
      url: "/fixtures/dal_1997_sct.txt",
      filingDate: "1997-09-19",
      profile: "summary_compensation",
    }),
  );

  // The in-flight request is rejected rather than left pending forever.
  expect(outcome.cancelKind).toBe("CancelledError");
  // The replacement worker is genuinely new: it initialised its own runtime.
  expect(outcome.reinitialized).toBe(true);
  // And it produces the right answer, not a degraded one.
  expect(outcome.afterRebuild.ok).toBe(true);
  expect(outcome.afterRebuild.rows).toHaveLength(15);
  expect(pick(outcome.afterRebuild, DAL_1997_ROLES)).toEqual(
    expect.arrayContaining([DAL_1997_EXPECTED[0]]),
  );
});

test("a queued request can be cancelled without losing the running one", async ({
  harness,
}) => {
  const kind = await harness.evaluate(() =>
    window.secBridge.cancelQueued({
      url: "/fixtures/dal_1997_sct.txt",
      filingDate: "1997-09-19",
      profile: "summary_compensation",
    }),
  );
  expect(kind).toBe("CancelledError");
});

test("repeated extraction leaks no PyProxy, no Python objects and no request state", async ({
  harness,
}) => {
  const [before, after] = await harness.evaluate(async () => {
    const call = {
      url: "/fixtures/azz_2019_ownership.html",
      filingDate: "2019-05-28",
      profile: "beneficial_ownership" as const,
    };
    await window.secBridge.extract(call);
    const before = await window.secBridge.diagnostics();
    for (let i = 0; i < 12; i++) await window.secBridge.extract(call);
    const after = await window.secBridge.diagnostics();
    return [before, after];
  });

  // The only proxies that exist are the four callables pinned at preparation;
  // an extraction returns a JSON string, so its steady-state cost is zero.
  expect(before.liveProxies).toBe(after.liveProxies);
  expect(after.liveProxies).toBe(4);
  // Python is not holding results either — this is counted by gc, not by us.
  expect(after.livePythonExtractions).toBe(0);
  // Nothing was written into the interpreter's global namespace.
  expect(after.strayPythonGlobals).toEqual([]);
  // No request left half-answered.
  expect(after.pendingRequests).toBe(0);
  expect(after.extractionsCompleted).toBe(before.extractionsCompleted + 12);
  expect(after.runtimeInitCount).toBe(1);
});
